-- AlterTable
ALTER TABLE "Test" ADD COLUMN IF NOT EXISTS "extractStatus" TEXT NOT NULL DEFAULT 'ready';
ALTER TABLE "Test" ADD COLUMN IF NOT EXISTS "rawAiResponse" TEXT;
ALTER TABLE "Test" ADD COLUMN IF NOT EXISTS "extractionError" TEXT;
